# Generated by Django 3.1.8 on 2021-05-13 12:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('code_url', models.URLField(max_length=250, verbose_name='URL Code')),
                ('host_url', models.URLField(max_length=250, verbose_name='URL Page')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('progresion', models.CharField(max_length=3, verbose_name='Progresion')),
            ],
        ),
    ]
