# Generated by Django 3.1.8 on 2021-04-22 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='ad0a16a3-9976-4c6e-8a91-759140d1fac1', on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='posts.category'),
            preserve_default=False,
        ),
    ]
